### ISSUE TITLE
Bug: Sticker note doesn't appear

### ISSUE THREAD

**Issue by m0urao** [alexwidua/figma-sticky-notes#1]
Hello, I  use this plugin daily but today I noticed that it has a bug. I've already restarted Figma, updated it, and even restarted my Mac.

What happens is that when I try to add a new stick note, only the shadow is added and nothing else.

<img width="1696" alt="Screenshot 2023-12-11 at 17 27 29" src="https://github.com/alexwidua/figma-sticky-notes/assets/91987141/9999a14f-8064-46b4-9e2c-ea8008372250">
<img width="1696" alt="Screenshot 2023-12-11 at 17 27 39" src="https://github.com/alexwidua/figma-sticky-notes/assets/91987141/e77b98f3-0706-4e3e-921f-c4befc9ed5a2">

**Comment by alexwidua** [comment]
Hey @m0urao,
seems like a Figma update broke the plugin in some way, I can reproduce the bug on my end. I'll look into it asap :-)

–Alex

**Comment by m0urao** [comment]
Hi @alexwidua, this is now working fine for me. :)
